name: ccramic
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.9.16
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - alabaster==0.7.13
    - anndata==0.9.1
    - anyio==3.7.0
    - app-model==0.1.4
    - appdirs==1.4.4
    - asttokens==2.2.1
    - async-generator==1.10
    - async-timeout==4.0.2
    - attrs==23.1.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - brotli==1.0.9
    - build==0.10.0
    - cachelib==0.9.0
    - cachey==0.2.1
    - certifi==2023.5.7
    - cffi==1.15.1
    - cfgv==3.3.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - comm==0.1.3
    - contourpy==1.0.7
    - coverage==7.2.7
    - cryptography==41.0.1
    - cycler==0.11.0
    - cython==0.29.35
    - dash==2.10.2
    - dash-ag-grid==2.3.0
    - dash-auth==2.0.0
    - dash-bootstrap-components==1.4.1
    - dash-canvas==0.1.0
    - dash-core-components==2.0.0
    - dash-daq==0.5.0
    - dash-draggable==0.1.2
    - dash-extensions==1.0.1
    - dash-google-auth==0.1.2
    - dash-html-components==2.0.0
    - dash-iconify==0.1.2
    - dash-mantine-components==0.12.1
    - dash-renderer==1.9.1
    - dash-table==5.0.0
    - dash-testing-stub==0.0.2
    - dash-uploader==0.7.0a1
    - dask==2023.5.1
    - debugpy==1.6.7
    - decorator==5.1.1
    - dill==0.3.6
    - diskcache==5.6.1
    - distlib==0.3.6
    - docstring-parser==0.15
    - docutils==0.17.1
    - easygui==0.98.3
    - editorconfig==0.12.3
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - filelock==3.12.0
    - flask==2.2.5
    - flask-autoindex==0.6.6
    - flask-caching==2.0.2
    - flask-compress==1.13
    - flask-dance==7.0.0
    - flask-httpauth==4.8.0
    - flask-silk==0.2
    - fonttools==4.39.4
    - fpdf==1.7.2
    - freeport==0.1.15
    - freetype-py==2.4.0
    - fsspec==2023.5.0
    - future==0.18.3
    - h11==0.14.0
    - h5py==3.8.0
    - heapdict==1.0.1
    - hsluv==5.0.3
    - httpcore==0.16.3
    - httpx==0.23.3
    - httpx-oauth==0.11.2
    - identify==2.5.24
    - idna==3.4
    - igraph==0.10.4
    - imagecodecs==2023.3.16
    - imageio==2.31.0
    - imagesize==1.4.1
    - imctools==2.1.8
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - in-n-out==0.1.7
    - iniconfig==2.0.0
    - ipykernel==6.23.1
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsbeautifier==1.14.8
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - leidenalg==0.9.1
    - llvmlite==0.40.0
    - locket==1.0.0
    - lxml==4.9.2
    - magicgui==0.7.2
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - more-itertools==9.1.0
    - multiprocess==0.70.14
    - mypy-extensions==1.0.0
    - napari==0.4.17
    - napari-console==0.0.8
    - napari-plugin-engine==0.2.0
    - napari-svg==0.1.8
    - natsort==8.3.1
    - nest-asyncio==1.5.6
    - networkx==3.1
    - nodeenv==1.8.0
    - npe2==0.7.0
    - numba==0.57.0
    - numpy==1.24.3
    - numpydoc==1.5.0
    - oauthlib==3.2.2
    - opencv-python-headless==4.7.0.72
    - orjson==3.9.0
    - outcome==1.2.0
    - packaging==21.3
    - pandas==2.0.2
    - parso==0.8.3
    - partd==1.4.0
    - patsy==0.5.3
    - percy==2.0.2
    - pexpect==4.8.0
    - phenograph==1.5.7
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pint==0.22
    - pkgconfig==1.5.5
    - platformdirs==3.5.1
    - plotly==5.14.1
    - pluggy==1.0.0
    - pre-commit==3.3.2
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - psygnal==0.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydantic==1.10.8
    - pygments==2.15.1
    - pynndescent==0.5.10
    - pyopengl==3.1.7
    - pyopenssl==23.2.0
    - pyparsing==3.0.9
    - pypdf==3.15.2
    - pyproject-hooks==1.0.0
    - pyrsistent==0.19.3
    - pysocks==1.7.1
    - pytest==7.3.1
    - pytest-cov==4.1.0
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - pytomlpp==1.0.13
    - pytz==2023.3
    - pyvips==2.2.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - readimc==0.6.2
    - redis==4.5.5
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3986==1.5.0
    - rich==13.4.1
    - scanpy==1.9.3
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sd-material-ui==4.6.0
    - seaborn==0.12.2
    - selenium==4.2.0
    - session-info==1.0.0
    - shapely==2.0.1
    - six==1.16.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4.1
    - sphinx==4.5.0
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stack-data==0.6.2
    - statsmodels==0.14.0
    - stdlib-list==0.8.0
    - superqt==0.4.1
    - svgpath2mpl==1.0.0
    - tenacity==8.2.2
    - texttable==1.6.7
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - tomli==2.0.1
    - toolz==0.12.0
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - trio==0.22.0
    - trio-websocket==0.10.2
    - typer==0.9.0
    - typing-extensions==4.6.3
    - tzdata==2023.3
    - umap-learn==0.5.3
    - urllib3==1.26.16
    - urllib3-secure-extra==0.1.0
    - urlobject==2.4.3
    - virtualenv==20.23.0
    - vispy==0.11.0
    - waitress==2.1.2
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - wsproto==1.2.0
    - xmltodict==0.13.0
    - xtiff==0.7.9
    - zipp==3.15.0
