name: ccramic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ccramic test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#      - uses: docker-practice/actions-setup-docker@master
#      - name: Build docker container and run preliminary checks
#        run: |
#          docker build -t ccramic:latest .
#          docker run ccramic:latest python3 --version && which ccramic
#        shell: bash -l {0}
#      - uses: eWaterCycle/setup-singularity@v7
#        with:
#            singularity-version: 3.11.0
#      - name: Build Singularity container and run preliminary checks
#        run: |
#          singularity build --fakeroot ccramic.sif Singularity
#          singularity exec ccramic.sif which ccramic && python3 --version
        # shell: bash -l {0} 
      - name: Install ccramic dependencies from requirements
        run: pip install -r requirements.txt
      - name: Install ccramic through pip after dependencies
        run: pip .
      - name: Run pytest for ccramic
        shell: bash -l {0}
        run: pytest --headless tests/

