name: rakaia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: rakaia test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#      - uses: docker-practice/actions-setup-docker@master
#      - name: Build docker container and run preliminary checks
#        run: |
#          docker build -t rakaia:latest .
#          docker run rakaia:latest python3 --version && which rakaia
#        shell: bash -l {0}
#      - uses: eWaterCycle/setup-singularity@v7
#        with:
#            singularity-version: 3.11.0
#      - name: Build Singularity container and run preliminary checks
#        run: |
#          singularity build --fakeroot rakaia.sif Singularity
#          singularity exec rakaia.sif which rakaia && python3 --version
        # shell: bash -l {0}
      - if: runner.os == 'Linux'
        run: sudo apt-get -y update && sudo apt-get install -y libgl1-mesa-dev
      # - name: Install rakaia dependencies from requirements
      #   run: pip install -r requirements.txt
      - name: Install rakaia through pip after dependencies
        run: pip install -e .
      - name: Check installed rakaia version
        run: rakaia -v
      - name: Run pytest for rakaia
        shell: bash -l {0}
        run: pytest --headless --cov=rakaia
